steps:
  - label: ":runner: Dynamically launch Pipelines"
    plugins:
      - staticfloat/forerunner#554da94e67f34d42728dfdec5c69b88b6f6240db:
          # This will create one job per project
          watch:
            - tutorials/**/*.jmd
            - tutorials/**/*.toml
          path_processor: .buildkite/path_processors/project-coalescing
          target: .buildkite/run_tutorial.yml
          target_type: template
      - staticfloat/forerunner#554da94e67f34d42728dfdec5c69b88b6f6240db:
          # This will create one job overall, throwing all path information away
          watch:
            - src/**/*.jl
            - "**/*.toml"
          target: .buildkite/test_sciml.yml
    agents:
      queue: "juliacpu"
      fastcpu: true
