name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'

      - uses: actions/cache@v1
        env:
          cache-name: cache-julia-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - uses: julia-actions/julia-buildpkg@latest

      - name: Build all
        run: julia --project -e 'using TuringTutorials; build_all()'
        env:
          # GitHub runners have 2 (modern) cores, so 2-6 threads should be ok.
          # Note that new Julia processes are spawned which also spawn multiple threads.
          JULIA_NUM_THREADS: 2

      - name: Remove .gitignore
        # Without this, the github-pages-deploy-action will ignore too many files.
        run: rm .gitignore

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          # Adds branch name suffix for pull request runs.
          branch: artifacts-${{ github.head_ref }}
          # To reduce state which eases debugging.
          clean: true
          # Deploy artifacts and code, allowing usage of `Pkg.develop` at turing.ml.
          folder: .

      - name: Fail if error in logs
        # Since it is such a long running job, it is preferable if errors do not crash the job.
        # Once everything is done, the job can exit with an error.
        run: echo 'TODO make it fail'
