name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - uses: julia-actions/julia-buildpkg@latest

      - name: Build all
        run: julia --project -e 'using TuringTutorials; build_all(; debug=true)'
        env:
          # GitHub runners have 2 (probably modern) cores, so 4 threads should work.
          JULIA_NUM_THREADS: 4

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: artifacts
          # To reduce state which eases debugging.
          clean: true
          # Can be prettier by only deploying artifacts and not code, but this will do for now.
          folder: .
